### ISSUE TITLE
Implement Password Endpoints in Backend.Secure

### ISSUE THREAD

**Issue by Klausmd5** [htl-grieskirchen-core/core#103]
Add Endpoint(s) to Backend.Secure where you save the provided password in the db (which might exist or not).
Also identify the pw type1!

**Comment by EinboeckFranz** [comment]
Can you specify pw type?

**Comment by Klausmd5** [comment]
webuntis-token, eduvidual-token, ladp-pw.. look in se (hopefully) existing DB!
