### ISSUE TITLE
Jayjo sei Pfuscherei behebn

### ISSUE THREAD

**Issue by littlegamer757** [htl-grieskirchen-core/core#157]
As seen in: https://github.com/htl-grieskirchen-core/core/issues/155#issuecomment-1336503377

**Comment by ungarmichael** [comment]
I glaub den komma schließen, oda @littlegamer757 ?

**Comment by littlegamer757** [comment]
Hobe ma nu ned ongschaut muass i gonz ehrlich sogn, dua i heid donn

**Comment by littlegamer757** [comment]
i glaub des konn ma so lossn
