### ISSUE TITLE
implement credentials saving in mainframe

### ISSUE THREAD

**Issue by CallMeAlasca** [htl-grieskirchen-core/core#161]
Einstiegsseitn - oiso der Stepper, der jz scho iwie aufgruafn wird, wo oba nix passiert. (Eduvidual, etc.)

WebUntis brauch ma nimma, des passiert über LDAP

**Comment by ungarmichael** [comment]
is do des _onboarding_ gmoant? aiso der stepper wöcha de credentials vo de ondaren platformen obfrogt

**Comment by CallMeAlasca** [comment]
> is do des _onboarding_ gmoant? aiso der stepper wöcha de credentials vo de ondaren platformen obfrogt

Comment entsprechend angepasst.
