### ISSUE TITLE
document architecture for future collaborators

### ISSUE THREAD

**Issue by ungarmichael** [htl-grieskirchen-core/core#199]
- i glaub es warad ned schlecht wonn ma den mainframe und wie a funktioniert a bissl dokumentiern datn (im wiki vom core projekt)

**Comment by CallMeAlasca** [comment]
Moanst du sowos? bzw. bitte ausführen, wie des gmand is

https://github.com/htl-grieskirchen-core/core/blob/979dcd4ba323db4e0df3fe86d0e149d0c6f89330/diagrams/architecture.puml

https://github.com/htl-grieskirchen-core/core/blob/979dcd4ba323db4e0df3fe86d0e149d0c6f89330/diagrams/backend-plugins.puml

**Comment by ungarmichael** [comment]
jo, moanst konn ma des in am gängigen image format im wiki vom projekt einedoa und a nu a weng genauer auf des mainframe system eigeh?

**Comment by CallMeAlasca** [comment]
https://github.com/htl-grieskirchen-core/core/wiki/Architektur-und-Funktionsweise Erstentwurf

**Comment by CallMeAlasca** [comment]
Gurtner sogt, bast nu ned.

**Comment by CallMeAlasca** [comment]
@ungarmichael bitte gach Reviewn, ob des fias Erste bast

**Comment by CallMeAlasca** [comment]
is kauft.
