### ISSUE TITLE
provide some doc on deployment

### ISSUE THREAD

**Issue by ungarmichael** [htl-grieskirchen-core/core#207]
- docker setup a weng erklären (im wiki) 
- damit moan i oafoch wos ma ois doa muas dass des projekt lauft (compose, env vars, ...)

**Comment by CallMeAlasca** [comment]
[Deployment Docs](https://github.com/htl-grieskirchen-core/core/wiki/Deployment)
nu nix gschriem, oba wern dort sei.

**Comment by ungarmichael** [comment]
@SchneckchenAndy konnst du do wos mocha?

**Comment by SchneckchenAndy** [comment]
Muas mim @profiluefter abgeklärt werden

**Comment by CallMeAlasca** [comment]
mocht da @Klausmd5 grod - oiso Deployment vorbereiten.

**Comment by CallMeAlasca** [comment]
schaut guad aus
