### ISSUE TITLE
Deployment-Test am Schulserver

### ISSUE THREAD

**Issue by CallMeAlasca** [htl-grieskirchen-core/core#208]
Vor ollem a klärn:
- Port-Freigabe
- Reverse Proxy
- https ?
- Github-Action so wie jz?

**Comment by ungarmichael** [comment]
griagn wahrscheinlich donn an server denn ma si in da klass konfigurieren

**Comment by CallMeAlasca** [comment]
Docker in ana VM is ned des Wahre - Professoren evaluieren, ob am Server Docker lauft; Deployment noch hinten vaschoben.

**Comment by Klausmd5** [comment]
vm geht. domains san nu massiv baustell

**Comment by ungarmichael** [comment]
wissts ihr scho wonn wir do hardware griagn?

**Comment by profiluefter** [comment]
goaned

**Comment by profiluefter** [comment]
klausl bereitet a VM vor
