### ISSUE TITLE
plugin backend in core backend integrieren

### ISSUE THREAD

**Issue by CallMeAlasca** [htl-grieskirchen-core/core#227]

**Comment by profiluefter** [comment]
oiso i kenn mi aktuell ned aus wos des hoassn soid

**Comment by CallMeAlasca** [comment]
gibt scho a boa Subtasks (URL konfigurierbar, etc)

**Comment by CallMeAlasca** [comment]
haut hie.
Momentan fragwürdig: Plugin Sqlite, Core MySQL
An sich wa a MySQL-DB fia de Plugins definiert, oba aufgrund von begrenzter Zeit is des guad gnuag.
