### ISSUE TITLE
Mehrere DBs zum Laufen bringa

### ISSUE THREAD

**Issue by CallMeAlasca** [htl-grieskirchen-core/core#228]
momentan ok, weil ma nur 1 Plugin hobn.
Bei mehrere Plugins und damit mehrere generishce DBs homma a Problem.

**Comment by profiluefter** [comment]
klausl kennt se scho aus und woit mas erklärn wosa herausgfundn hod oba i hobs imma nu ned checkt

**Comment by Klausmd5** [comment]
> klausl kennt se scho aus und woit mas erklärn wosa herausgfundn hod oba i hobs imma nu ned checkt

Gonz hinterhältig fu hintn dastochn woan 😵

**Comment by profiluefter** [comment]
passiert

**Comment by Klausmd5** [comment]
https://github.com/htl-grieskirchen-core/core/commit/960c5067331149c34a51a5d94d46a131c59527af
