### ISSUE TITLE
Architektur-Diagramm puml updaten

### ISSUE THREAD

**Issue by CallMeAlasca** [htl-grieskirchen-core/core#239]

**Comment by SchneckchenAndy** [comment]
Siehe Wiki und diagrams folder 6d3026159c1dab0eba91d23341605f8e40304c81

Diagramm: [plantuml.com](http://www.plantuml.com/plantuml/png/PP9DJiCm48NtSugvG6w0KAd20WcaIgXYWLYCxMaLDPr8_e45ukx4jEFQU1NFzvwVCY_PX4W-flCCPEFYSH_O0tYsaUGuCsxzyhKY_0P4bCKnlj0a1qzdBcGtf-Cay0FWA9AXmEWClcSTHueiXkG47m2LUqlsnEBqXkBnEbwihsoJPxN-eUVnOVSaaVs1xDNrncOlSGh_yADBdvDBDDzulTWQ4wgjSguE9R40rgoyPAve6Ewh8iffoBnzwwBThPfMTNdWZQYxcLIlUsd2izvltv7QrWVqFK6Fif6LzXdjLsacbVjBpi1cFUP_xnS0)
