### ISSUE TITLE
Favourite plugins aus mainframe config entfernen

### ISSUE THREAD

**Issue by CallMeAlasca** [htl-grieskirchen-core/core#258]
https://github.com/htl-grieskirchen-core/core/wiki/Plugins-im-Frontend-laden#plugin-liste mocht, wie da Andi angmerkt hod, ned so vü Sinn, dass wir isFavourite global setzen.
Evaluiern, ob wir beim User a Listn vu Plugin-Ids speichan kinnan, de daun favourite san.

**Comment by SchneckchenAndy** [comment]
Aus docs entfernt: https://github.com/htl-grieskirchen-core/core/wiki/Plugins-im-Frontend-laden#plugin-liste

**Comment by SchneckchenAndy** [comment]
Hob woatn miasn auf #263
