### ISSUE TITLE
frontend - look into angular with tailwind css

### ISSUE THREAD

**Issue by littlegamer757** [htl-grieskirchen-core/core#40]

**Comment by littlegamer757** [comment]
https://tailwindcss.com/docs/guides/angular

**Comment by littlegamer757** [comment]
https://tailwindcss.com/docs/configuration

**Comment by ungarmichael** [comment]
wie schauma do aus?

**Comment by littlegamer757** [comment]
guad, PR hobe vor 3 min gmocht
@profiluefter wie schauma do aus?
