### ISSUE TITLE
evaluate necessary information to realize mockups

### ISSUE THREAD

**Issue by CallMeAlasca** [htl-grieskirchen-core/core#55]

**Comment by ungarmichael** [comment]
um wos gehts do?

**Comment by CallMeAlasca** [comment]
wöche Informationen wir zentral z.B. zu de Plugins brauchn, Einstellungen, etc.

**Comment by CallMeAlasca** [comment]
Plugin-Infos
Fälligkeit
betroffene Gruppen (KVs, Religionslehrer, Freigegenstände, Klassen - teilweise von AD)
Bild
Titel
Tags/Schlagwörter (neu erstellbar oder fix)

Favoriten per Nutzer

Einstellungen
Benachrichtigungen
Anmeldedaten

eigenes Plugin?:
Zitate -> Zitat des Tages
Einreichen & wählen
Zitate selbst im Core-Projekt
